services:
# 云服务器上本地起的mysql，没用上docker
  mysql:
    image: "mysql:latest"
    container_name: mysql01 # 容器名称
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ZZYzzy4771430///
      - MYSQL_DATABASE=antarctic_data
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
    restart: always

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
